'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Buyout
    Public Property Id As Integer
    Public Property Quantity As String
    Public Property [Date] As String
    Public Property IdUser As Integer
    Public Property ProductId As Integer

    Public Overridable Property User As User
    Public Overridable Property Product As Product

End Class
