'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Company
    Public Property Id As Integer
    Public Property CreateAt As Date
    Public Property DeleteAt As Date
    Public Property UpdateAt As Date
    Public Property Description As String
    Public Property NameCompany As String
    Public Property PhoneCompany As Short
    Public Property EmailCompany As String
    Public Property NitCompany As Short
    Public Property Status As Boolean
    Public Property Logo As String

    Public Overridable Property Sede As ICollection(Of Sede) = New HashSet(Of Sede)
    Public Overridable Property User As ICollection(Of User) = New HashSet(Of User)

End Class
