'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Inventory
    Public Property Id As Integer
    Public Property NameInventory As String
    Public Property Status As String
    Public Property Observation As String
    Public Property CreateAt As String
    Public Property DeleteAt As String
    Public Property UpdateAt As String
    Public Property StockActual As String
    Public Property ZoneProduct As String
    Public Property IdProduct As Integer

    Public Overridable Property MovimientoItemInventory As ICollection(Of MovimientoInventory) = New HashSet(Of MovimientoInventory)
    Public Overridable Property Product As ICollection(Of Product) = New HashSet(Of Product)

End Class
