'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Model1Container
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Model1Container")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property FormSet() As DbSet(Of Form)
    Public Overridable Property ModuleSet() As DbSet(Of [Module])
    Public Overridable Property RolFormSet() As DbSet(Of RolForm)
    Public Overridable Property RolSet() As DbSet(Of Rol)
    Public Overridable Property UserSet() As DbSet(Of User)
    Public Overridable Property PersonSet() As DbSet(Of Person)
    Public Overridable Property SedeSet() As DbSet(Of Sede)
    Public Overridable Property CompanySet() As DbSet(Of Company)
    Public Overridable Property Items() As DbSet(Of Product)
    Public Overridable Property ImageProductSet() As DbSet(Of ImageProduct)
    Public Overridable Property Inventorys() As DbSet(Of Inventory)
    Public Overridable Property CategorySet() As DbSet(Of Category)
    Public Overridable Property MovimientoInventorySet() As DbSet(Of MovimientoInventory)
    Public Overridable Property Buyouts() As DbSet(Of Buyout)
    Public Overridable Property Sales() As DbSet(Of Sale)
    Public Overridable Property SaleDetailSet() As DbSet(Of SaleDetail)
    Public Overridable Property Notifications() As DbSet(Of Notification)

End Class
