'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class [Module]
    Public Property Id As Integer
    Public Property NameModule As String
    Public Property Status As Boolean

    Public Overridable Property Form As ICollection(Of Form) = New HashSet(Of Form)

End Class
