'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Notification
    Public Property Id As Integer
    Public Property TypeAction As String
    Public Property IdReferece As String
    Public Property Mensage As String
    Public Property Read As String
    Public Property [Date] As String
    Public Property UserId As Integer

    Public Overridable Property User As User

End Class
