'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Person
    Public Property Id As Integer
    Public Property first_name As String
    Public Property last_name As String
    Public Property phone_number As Short
    Public Property email As String
    Public Property type_identification As String
    Public Property number_identification As Short
    Public Property status As String

    Public Overridable Property User As User

End Class
