'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property Id As Integer
    Public Property NameProduct As String
    Public Property Description As String
    Public Property Price As String
    Public Property CreateAt As String
    Public Property DeleteAt As String
    Public Property UpdateAt As String
    Public Property Status As String
    Public Property IdInventory As Integer

    Public Overridable Property ImageItem As ImageProduct
    Public Overridable Property Category As Category
    Public Overridable Property Buyout As ICollection(Of Buyout) = New HashSet(Of Buyout)
    Public Overridable Property MovimientoInventory As ICollection(Of MovimientoInventory) = New HashSet(Of MovimientoInventory)
    Public Overridable Property SaleDetail As ICollection(Of SaleDetail) = New HashSet(Of SaleDetail)
    Public Overridable Property Inventory As Inventory

End Class
