'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Rol
    Public Property Id As Integer
    Public Property NameRol As String
    Public Property Description As String
    Public Property Status As Boolean

    Public Overridable Property User As User
    Public Overridable Property RolForm As ICollection(Of RolForm) = New HashSet(Of RolForm)

End Class
