'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RolForm
    Public Property Id As Integer
    Public Property Permision As Integer
    Public Property IdForm As Integer
    Public Property IdRol As Integer

    Public Overridable Property Form As Form
    Public Overridable Property Rol As Rol

End Class
