'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sale
    Public Property Id As Integer
    Public Property [Date] As String
    Public Property totaly As String
    Public Property IdUser As Integer

    Public Overridable Property User As User
    Public Overridable Property SaleDetail As ICollection(Of SaleDetail) = New HashSet(Of SaleDetail)

End Class
