'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SaleDetail
    Public Property Id As Integer
    Public Property Quantity As String
    Public Property IdSale As Integer
    Public Property IdProduct As Integer

    Public Overridable Property Sale As Sale
    Public Overridable Property Product As Product

End Class
