'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sede
    Public Property Id As Integer
    Public Property NameSede As String
    Public Property CodeSede As Long
    Public Property AddressSede As String
    Public Property PhoneSede As Short
    Public Property EmailSede As String
    Public Property Status As Boolean
    Public Property CreateAt As Date
    Public Property DeleteAt As Date
    Public Property UpdateAt As Date
    Public Property IdCompany As Integer

    Public Overridable Property Company As Company

End Class
