'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class User
    Public Property Id As Integer
    Public Property Username As String
    Public Property Password As String
    Public Property CreateAt As String
    Public Property DeleteAt As String
    Public Property Status As String
    Public Property UpdateAt As String
    Public Property CompanyId As Integer

    Public Overridable Property Rol As Rol
    Public Overridable Property Person As Person
    Public Overridable Property Buyout As ICollection(Of Buyout) = New HashSet(Of Buyout)
    Public Overridable Property MovimientoInventory As ICollection(Of MovimientoInventory) = New HashSet(Of MovimientoInventory)
    Public Overridable Property Sale As ICollection(Of Sale) = New HashSet(Of Sale)
    Public Overridable Property Notification As ICollection(Of Notification) = New HashSet(Of Notification)
    Public Overridable Property Company As Company

End Class
